#!/usr/bin/env bash
# Move the local corpus into a Neon project.
#
# Reads NEON_ADMIN_URL from .env (gitignored). Nothing here echoes a
# connection string or a generated password to stdout -- passwords are written
# straight into .env for you to copy into Vercel.
#
# Idempotent enough to re-run: roles are created only if absent, and the
# restore targets an empty schema, so re-running means dropping first.
set -euo pipefail
cd "$(dirname "$0")/.."

[ -f .env ] || { echo "no .env -- see the header of this script"; exit 2; }

# Read .env by parsing, not by sourcing. A Neon connection string carries
# `&channel_binding=...`, and `. ./.env` hands that to the shell as a job
# control operator -- the whole file fails to parse and every value is empty.
# `|| true`: a miss must return empty, not fail. Without it `set -e` kills the
# script on the first optional key, before its default can apply.
envget() { grep -E "^$1=" .env | head -1 | cut -d= -f2- || true ; }

NEON_ADMIN_URL=$(envget NEON_ADMIN_URL)
: "${NEON_ADMIN_URL:?set NEON_ADMIN_URL in .env}"

# Neon gives you two endpoints. The -pooler one runs PgBouncer in transaction
# mode, which cannot carry session state or a pg_dump restore, so all DDL and
# the migration go over the DIRECT endpoint. Strip the suffix if it is there.
DIRECT_URL="${NEON_ADMIN_URL/-pooler./.}"
POOLED_HOST=$(printf '%s' "$NEON_ADMIN_URL" | sed -E 's|.*@([^/]+)/.*|\1|')
DIRECT_HOST=$(printf '%s' "$DIRECT_URL"     | sed -E 's|.*@([^/]+)/.*|\1|')

LOCAL_DSN=$(envget DATABASE_URL_LOCAL)
# 5432, not the host-side 55432: pg_dump runs INSIDE the container, where
# localhost is the container and Postgres listens on its own port.
LOCAL_DSN="${LOCAL_DSN:-postgresql://postgres:dev@localhost:5432/postgres}"
# psql/pg_dump run inside the dev container: no local postgres client, and the
# container can reach Neon over the network just as well.
PG() { docker exec -i archive-dev "$@"; }

say() { printf '\n\033[1m%s\033[0m\n' "$*"; }

say "1/5  version check (pg_dump must not be older than the server)"
PG pg_dump --version
PG psql "$DIRECT_URL" -tAc "select version()" | cut -c1-40

say "2/5  roles"
APP_PW=$(openssl rand -hex 24); READ_PW=$(openssl rand -hex 24); AUTH_PW=$(openssl rand -hex 24)
PG psql "$DIRECT_URL" -v ON_ERROR_STOP=1 -q <<SQL
DO \$\$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='arch_app')  THEN CREATE ROLE arch_app  LOGIN; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='arch_read') THEN CREATE ROLE arch_read LOGIN NOINHERIT; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='arch_auth') THEN CREATE ROLE arch_auth LOGIN NOINHERIT; END IF;
END \$\$;
ALTER ROLE arch_app  PASSWORD '$APP_PW';
ALTER ROLE arch_read PASSWORD '$READ_PW';
ALTER ROLE arch_auth PASSWORD '$AUTH_PW';
SQL

say "3/5  schema + data"
# Reset the target explicitly instead of using pg_dump --clean. That flag
# emits CREATE OR REPLACE VIEW stubs in its cleanup section which reference
# enum types before creating them -- harmless against a populated database,
# fatal against an empty one, which is exactly the case here.
PG psql "$DIRECT_URL" -v ON_ERROR_STOP=1 -q -c \
  'DROP SCHEMA IF EXISTS public CASCADE; CREATE SCHEMA public;'
# Full dump rather than schema.sql + a data-only pass: --data-only gives no
# guarantee of foreign-key-safe ordering, and --disable-triggers needs a
# superuser Neon does not hand out. Roles already exist above, which is what
# the RLS policies (TO arch_auth) need in order to restore.
PG pg_dump "$LOCAL_DSN" --no-owner --no-privileges \
  | PG psql "$DIRECT_URL" -v ON_ERROR_STOP=1 -q

say "4/5  grants and policies for the three roles"
PG psql "$DIRECT_URL" -v ON_ERROR_STOP=1 -q < db/roles.sql
PG psql "$DIRECT_URL" -v ON_ERROR_STOP=1 -q <<'SQL'
GRANT USAGE ON SCHEMA public TO arch_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO arch_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO arch_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO arch_app;
SQL

say "5/5  verify against the local corpus"
for t in source_document source_page doc_node knowledge_item citation chunk item_term; do
  L=$(PG psql "$LOCAL_DSN" -tAc "set app.account_id='00000000-0000-0000-0000-0000000000aa'; select count(*) from $t" | tail -1)
  R=$(PG psql "$DIRECT_URL" -tAc "set app.account_id='00000000-0000-0000-0000-0000000000aa'; select count(*) from $t" | tail -1)
  [ "$L" = "$R" ] && printf "  ok    %-18s %s\n" "$t" "$R" || printf "  FAIL  %-18s local=%s neon=%s\n" "$t" "$L" "$R"
done

DBN=$(printf '%s' "$DIRECT_URL" | sed -E 's|.*/([^?]+)(\?.*)?$|\1|')
{
  echo ""
  echo "# generated by scripts/load_neon.sh -- copy these into Vercel"
  # The web app sets app.account_id with SET LOCAL inside a transaction, which
  # is safe through the pooler. tools/db.py uses session-scoped set_config, so
  # the Python side must NOT go through it -- hence two shapes here.
  echo "NEON_DATABASE_URL=postgresql://arch_app:$APP_PW@$POOLED_HOST/$DBN?sslmode=require"
  echo "NEON_DATABASE_URL_READONLY=postgresql://arch_read:$READ_PW@$POOLED_HOST/$DBN?sslmode=require"
  echo "NEON_AUTH_DB_URL=postgresql://arch_auth:$AUTH_PW@$POOLED_HOST/$DBN?sslmode=require"
  echo "NEON_DIRECT_URL_ARCH_APP=postgresql://arch_app:$APP_PW@$DIRECT_HOST/$DBN?sslmode=require"
} >> .env
say "done -- three connection strings appended to .env (gitignored)"
